variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version


image: 'maven:latest'

stages:
  - build
  - test
  - deploy

test:
  stage: test
  script:
    - echo "We are testing your project, $GITLAB_USER_LOGIN"
    - mvn test -f management-framework -N

build:
    stage: build
    script:
     - echo "We are building your project, $GITLAB_USER_LOGIN"
     - mvn clean install -f management-framework -N
