variables:
  MAVEN_OPTS: >-
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version


image: 'maven:3.8.5-openjdk-21-slim'

stages:
  - build
  - test
  - deploy

build:
    tags:
     - shared-fi
    stage: build
    script:
     - echo "We are building your project, $GITLAB_USER_LOGIN"
     - ./mvnw clean install $MAVEN_CLI_OPTS
     
test:
    tags:
     - shared-fi
    stage: test
    script:
     - echo "We are testing your project, $GITLAB_USER_LOGIN"
     - ./mvnw test $MAVEN_CLI_OPTS
